/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Db
         * @description Verifica tablas billing + chat; 503 si faltan tablas críticas de chat.
         */
        get: operations["health_db_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Login */
        post: operations["auth_login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Refresh */
        post: operations["auth_refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auth Logout */
        post: operations["auth_logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/revoke-user-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Revoke User Tokens */
        post: operations["admin_revoke_user_tokens_v1_admin_revoke_user_tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Profile Route */
        get: operations["get_user_profile_route_users_me_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch User Profile Route */
        patch: operations["patch_user_profile_route_users_me_profile_patch"];
        trace?: never;
    };
    "/oauth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Oauth Google Start */
        post: operations["oauth_google_start_oauth_google_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oauth Google Callback */
        get: operations["oauth_google_callback_oauth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/google/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Oauth Google Status
         * @description Retorna el estado de la vinculacion OAuth Google del usuario autenticado.
         */
        get: operations["oauth_google_status_oauth_google_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/agenda/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat Agenda Today */
        get: operations["chat_agenda_today_v1_chat_agenda_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Chat Reminder */
        post: operations["create_chat_reminder_v1_chat_reminders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/reminders/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Chat Reminders */
        get: operations["list_pending_chat_reminders_v1_chat_reminders_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/reminders/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ack Chat Reminders */
        post: operations["ack_chat_reminders_v1_chat_reminders_ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Translate */
        post: operations["chat_translate_v1_chat_translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Summarize */
        post: operations["chat_summarize_v1_chat_summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Send */
        post: operations["chat_send_v1_chat_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/send/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Send Stream
         * @description Responde al chat con streaming SSE.
         *     La respuesta se transmite token por token via Server-Sent Events.
         */
        post: operations["chat_send_stream_v1_chat_send_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/{conversation_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chat History
         * @description Obtiene historial real de conversación desde BD.
         */
        get: operations["chat_history_v1_chat__conversation_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chat List
         * @description Lista conversaciones del usuario.
         */
        get: operations["chat_list_v1_chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Document */
        post: operations["generate_document_v1_documents_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_v1_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_v1_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/templates/{template_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Template */
        post: operations["render_template_v1_templates__template_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/telemetry/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Telemetry Event
         * @description Recibe evento de telemetria anonimo del cliente.
         */
        post: operations["telemetry_event_v1_telemetry_event_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Capabilities
         * @description Lista capacidades disponibles segun el plan del cliente autenticado.
         */
        get: operations["list_capabilities_v1_capabilities__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities/{capability_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capability Detail
         * @description Detalle de una capacidad especifica.
         */
        get: operations["get_capability_detail_v1_capabilities__capability_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/automations/{auto_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Automation
         * @description Ejecuta una automatizacion inmediatamente (trigger manual).
         *
         *     Busca la automatizacion en el perfil del usuario y la ejecuta.
         */
        post: operations["execute_automation_v1_automations__auto_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/automations/{auto_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Automation History
         * @description Devuelve historial de ejecuciones de una automatizacion.
         */
        get: operations["get_automation_history_v1_automations__auto_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/automations/results/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack Pending Results
         * @description Marca los resultados pendientes como leidos.
         */
        post: operations["ack_pending_results_v1_automations_results_ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/automations/results/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pending Results
         * @description Devuelve metadata de resultados pendientes para notificación desktop.
         */
        get: operations["get_pending_results_v1_automations_results_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pendrive/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Pendrive
         * @description Verifica server-side que el serial pertenece a un cliente registrado.
         */
        post: operations["verify_pendrive_v1_pendrive_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pendrive/recovery-backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backup Recovery Key
         * @description Guarda la recovery key del vault en Firestore (cifrada con Fernet).
         *     El cliente debe estar autenticado con JWT.
         */
        post: operations["backup_recovery_key_v1_pendrive_recovery_backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pendrive/recovery/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recovery
         * @description Recupera la recovery key del vault desde Firestore.
         *     El propio cliente autenticado puede ver su recovery key.
         */
        get: operations["get_recovery_v1_pendrive_recovery__cliente_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Recovery
         * @description Elimina el backup de recovery key de Firestore (solo el propio usuario).
         */
        delete: operations["delete_recovery_v1_pendrive_recovery__cliente_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pendrive/challenge/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Challenge
         * @description Solicita un nonce criptográfico para iniciar el handshake del pendrive.
         */
        post: operations["request_challenge_v1_pendrive_challenge_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pendrive/challenge/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Challenge
         * @description Verifica la firma HMAC-SHA256 del nonce usando el hardware_token_hash del usuario.
         */
        post: operations["verify_challenge_v1_pendrive_challenge_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pendrive/recovery-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recovery Login
         * @description Login alternativo usando recovery key cuando se pierde el pendrive.
         *     Emite un JWT de 24h con claim hardware_required=false para permitir
         *     vincular un nuevo pendrive sin necesidad del original.
         */
        post: operations["recovery_login_v1_pendrive_recovery_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pendrive/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link New Pendrive
         * @description Vincula un nuevo pendrive a la cuenta del usuario autenticado.
         *     Requiere JWT valido (incluyendo recovery JWT con hardware_required=false).
         */
        post: operations["link_new_pendrive_v1_pendrive_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/pendrive/provisioning/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin List Provisioning Clients
         * @description Lista clientes activos aptos para provisión de pendrive.
         */
        get: operations["admin_list_provisioning_clients_v1_admin_pendrive_provisioning_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/pendrive/provisioning/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Validate Provisioning Serial
         * @description Valida serial para provisión y opcionalmente confirma la provisión.
         */
        post: operations["admin_validate_provisioning_serial_v1_admin_pendrive_provisioning_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/pendrive/recovery/{cliente_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Get Recovery
         * @description Recupera la recovery key del vault desde Firestore.
         *     Solo accesible con X-Admin-Key configurado en settings.admin_api_key.
         *     Útil para el panel admin (auto-venta1).
         */
        get: operations["admin_get_recovery_v1_admin_pendrive_recovery__cliente_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usb/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usb Devices
         * @description Lista USB conectados en el equipo local y cliente registrado por serial.
         */
        get: operations["get_usb_devices_v1_usb_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usb/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision Usb
         * @description Ejecuta provisión de entrega (vault + verificación + instalador opcional).
         */
        post: operations["provision_usb_v1_usb_provision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usb/client-by-serial/{serial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client By Serial
         * @description Devuelve cédula y nombre del cliente vinculado al serial USB.
         */
        get: operations["get_client_by_serial_v1_usb_client_by_serial__serial__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whatsapp/channel/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Obtiene el estado actual del canal WhatsApp del usuario autenticado.
         */
        get: operations["get_status_v1_whatsapp_channel_status_get"];
        put?: never;
        /**
         * Update Status
         * @description Actualiza el estado del canal WhatsApp (linked, phone, error).
         */
        post: operations["update_status_v1_whatsapp_channel_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whatsapp/channel/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Event
         * @description Registra un evento operacional del canal (qr_ready, linked, disconnected, etc.).
         */
        post: operations["post_event_v1_whatsapp_channel_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whatsapp/channel/reconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconnect
         * @description Limpia el estado del canal y reinicia a disconnected.
         */
        post: operations["reconnect_v1_whatsapp_channel_reconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgendaEventResponse */
        AgendaEventResponse: {
            /** Summary */
            summary: string;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Html Link */
            html_link?: string | null;
        };
        /** AgendaTodayResponse */
        AgendaTodayResponse: {
            /** Linked */
            linked: boolean;
            /** Events */
            events: components["schemas"]["AgendaEventResponse"][];
            /** Message */
            message: string;
        };
        /** AiCredentialsPatch */
        AiCredentialsPatch: {
            /** Provider Id */
            provider_id: string;
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
        };
        /** AiCredentialsResponse */
        AiCredentialsResponse: {
            /** Provider Id */
            provider_id: string;
            /** Username */
            username?: string | null;
            /**
             * Has Password
             * @default false
             */
            has_password: boolean;
        };
        /** ChallengeRequestResponse */
        ChallengeRequestResponse: {
            /** Nonce */
            nonce: string;
        };
        /** ChallengeVerifyRequest */
        ChallengeVerifyRequest: {
            /** Nonce */
            nonce: string;
            /** Signature */
            signature: string;
        };
        /** ChallengeVerifyResponse */
        ChallengeVerifyResponse: {
            /** Ok */
            ok: boolean;
        };
        /** ChatMessageResponse */
        ChatMessageResponse: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Text */
            text: string;
            /** Createdat */
            createdAt: string;
            /**
             * Status
             * @default sent
             */
            status: string;
        };
        /** ClientBySerialResponse */
        ClientBySerialResponse: {
            /** Ok */
            ok: boolean;
            /** Serial */
            serial: string;
            /** Cedula */
            cedula?: string | null;
            /** Nombre */
            nombre?: string | null;
            /** Uid */
            uid?: string | null;
            /** Error */
            error?: string | null;
        };
        /** DocumentTemplateItem */
        DocumentTemplateItem: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Document Type */
            document_type: string;
            /** Structure */
            structure: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ExecuteResponse */
        ExecuteResponse: {
            /** Success */
            success: boolean;
            /** Result */
            result: string;
            /** Executed At */
            executed_at: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * Document Type
             * @description Tipo: docx, xlsx, txt
             */
            document_type: string;
            /**
             * Title
             * @description Nombre del archivo sin extension
             */
            title: string;
            /**
             * Content
             * @description Contenido del documento en markdown/texto plano
             */
            content: string;
            /**
             * Folder
             * @description Subcarpeta dentro de DOT Trabajos
             */
            folder?: string | null;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /** Ok */
            ok: boolean;
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Document Type */
            document_type: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** GoogleOAuthStartBody */
        GoogleOAuthStartBody: {
            /**
             * Integrations
             * @description Integraciones Google: "gmail" y/o "google-calendar" (scopes por separado).
             */
            integrations?: string[] | null;
            /**
             * Firebase Id Token
             * @description Opcional/desaconsejado: ID token Firebase. Preferir Bearer JWT DOT.
             */
            firebase_id_token?: string | null;
            /**
             * Dev User Id
             * @description Solo si ALLOW_OAUTH_DEV_WITHOUT_FIREBASE_AUTH=1 -- ej. UUID de cliente de prueba.
             */
            dev_user_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryItem */
        HistoryItem: {
            /** Executed At */
            executed_at: string;
            /** Result */
            result: string;
            /** Output Type */
            output_type: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Executions */
            executions: components["schemas"]["HistoryItem"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Cedula */
            cedula: string;
            /**
             * Password
             * @description Mapeado a clave_acceso en la BD.
             */
            password: string;
            /**
             * Hardware Serial
             * @description Serial de fábrica del pendrive; lo lee la app de escritorio en esta PC.
             */
            hardware_serial?: string | null;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            cliente: components["schemas"]["SuscripcionClienteDto"];
        };
        /** LogoutRequest */
        LogoutRequest: {
            /**
             * Refresh Token
             * @description Opcional: revocar también la familia de refresh.
             */
            refresh_token?: string | null;
        };
        /** MeResponse */
        MeResponse: {
            /** Uid */
            uid: string;
            /** Cedula */
            cedula?: string | null;
            /** Email */
            email?: string | null;
            /** Plan */
            plan?: string | null;
            /** Fecha Vencimiento */
            fecha_vencimiento?: string | null;
            /** Email Verified */
            email_verified?: boolean | null;
        };
        /** PendingResultsResponse */
        PendingResultsResponse: {
            /**
             * Has New
             * @default false
             */
            has_new: boolean;
            /** Last Auto Id */
            last_auto_id?: string | null;
            /** Last Auto Name */
            last_auto_name?: string | null;
            /** Last Executed At */
            last_executed_at?: string | null;
            /** Last Result Preview */
            last_result_preview?: string | null;
        };
        /** PendriveLinkRequest */
        PendriveLinkRequest: {
            /** Serial */
            serial: string;
        };
        /** PendriveLinkResponse */
        PendriveLinkResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
        };
        /** PendriveVerifyRequest */
        PendriveVerifyRequest: {
            /** Serial */
            serial: string;
            /** Drive Path */
            drive_path?: string | null;
        };
        /** PendriveVerifyResponse */
        PendriveVerifyResponse: {
            /** Ok */
            ok: boolean;
            /** Serial Hash */
            serial_hash?: string | null;
            /** Uid */
            uid?: string | null;
            /** Cedula */
            cedula?: string | null;
            /** Nombre */
            nombre?: string | null;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
        };
        /** ProvisioningClientItem */
        ProvisioningClientItem: {
            /** Uid */
            uid: string;
            /** Cedula */
            cedula: string;
            /** Nombre */
            nombre: string;
            /** Estado */
            estado: string;
            /** Has Hardware Linked */
            has_hardware_linked: boolean;
        };
        /** ProvisioningClientsResponse */
        ProvisioningClientsResponse: {
            /** Ok */
            ok: boolean;
            /** Count */
            count: number;
            /** Clients */
            clients: components["schemas"]["ProvisioningClientItem"][];
        };
        /** ProvisioningValidateRequest */
        ProvisioningValidateRequest: {
            /** Uid */
            uid: string;
            /** Serial */
            serial: string;
            /**
             * Mark Completed
             * @default false
             */
            mark_completed: boolean;
        };
        /** ProvisioningValidateResponse */
        ProvisioningValidateResponse: {
            /** Ok */
            ok: boolean;
            /** Uid */
            uid: string;
            /** Cedula */
            cedula: string;
            /** Nombre */
            nombre: string;
            /** Estado */
            estado: string;
            /** Has Hardware Linked */
            has_hardware_linked: boolean;
            /** Serial Matches */
            serial_matches: boolean;
            /** Provision Completed */
            provision_completed: boolean;
            /** Message */
            message?: string | null;
            /** Error */
            error?: string | null;
        };
        /** RecoveryBackupRequest */
        RecoveryBackupRequest: {
            /** Recovery Key */
            recovery_key: string;
        };
        /** RecoveryLoginRequest */
        RecoveryLoginRequest: {
            /** Cedula */
            cedula: string;
            /** Password */
            password: string;
            /** Recovery Key */
            recovery_key: string;
        };
        /** RecoveryResponse */
        RecoveryResponse: {
            /** Ok */
            ok: boolean;
            /** Recovery Key */
            recovery_key?: string | null;
            /** Error */
            error?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RefreshResponse */
        RefreshResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** RegisteredClienteSummary */
        RegisteredClienteSummary: {
            /** Uid */
            uid: string;
            /** Cedula */
            cedula: string;
            /** Nombre */
            nombre: string;
        };
        /** ReminderAckRequest */
        ReminderAckRequest: {
            /**
             * Ids
             * @default []
             */
            ids: string[];
        };
        /** ReminderCreateRequest */
        ReminderCreateRequest: {
            /** Text */
            text: string;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
        };
        /** ReminderCreateResponse */
        ReminderCreateResponse: {
            /** Ok */
            ok: boolean;
            /** Id */
            id: string;
            /** Due At */
            due_at: string;
            /** Message */
            message: string;
        };
        /** ReminderPendingItem */
        ReminderPendingItem: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Due At */
            due_at: string;
        };
        /** ReminderPendingResponse */
        ReminderPendingResponse: {
            /** Reminders */
            reminders: components["schemas"]["ReminderPendingItem"][];
        };
        /** RevokeUserTokensRequest */
        RevokeUserTokensRequest: {
            /** Uid */
            uid: string;
        };
        /**
         * SavedAutomationDto
         * @description AutomationDTO del contrato v1 — snake_case en JSON de API y Firestore.
         */
        SavedAutomationDto: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Integration Id */
            integration_id: string;
            /** Instruction */
            instruction: string;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Output Type */
            output_type?: string | null;
            /** Schedule */
            schedule?: string | null;
            /** Description */
            description?: string | null;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Text */
            text: string;
            /** Provider */
            provider?: string | null;
        };
        /** SendMessageResponse */
        SendMessageResponse: {
            message: components["schemas"]["ChatMessageResponse"];
            /** Conversation Id */
            conversation_id: string;
            /**
             * History Saved
             * @default true
             */
            history_saved: boolean;
        };
        /** SummarizeRequest */
        SummarizeRequest: {
            /** Content */
            content: string;
            /** Provider */
            provider?: string | null;
        };
        /** SummarizeResponse */
        SummarizeResponse: {
            /** Summary */
            summary: string;
            /** Source Type */
            source_type: string;
            /** Chunks */
            chunks: number;
        };
        /** SuscripcionClienteDto */
        SuscripcionClienteDto: {
            /**
             * Cliente Id
             * @description UUID en clientes_suscripcion.id
             */
            cliente_id: string;
            /** Cedula */
            cedula: string;
            /** Plan */
            plan: string;
            /**
             * Fecha Vencimiento
             * Format: date
             */
            fecha_vencimiento: string;
            /** Correo */
            correo?: string | null;
        };
        /** TelemetryEvent */
        TelemetryEvent: {
            /** Type */
            type: string;
            /** Timestamp */
            timestamp: string;
            /**
             * Meta
             * @default {}
             */
            meta: {
                [key: string]: unknown;
            };
        };
        /** TemplateCreateRequest */
        TemplateCreateRequest: {
            /** Name */
            name: string;
            /**
             * Document Type
             * @description docx, xlsx, txt
             */
            document_type: string;
            /** Structure */
            structure: string;
        };
        /** TemplateListResponse */
        TemplateListResponse: {
            /** Templates */
            templates: components["schemas"]["DocumentTemplateItem"][];
        };
        /** TemplateRenderRequest */
        TemplateRenderRequest: {
            /** User Input */
            user_input: string;
            /** Provider */
            provider?: string | null;
        };
        /** TemplateRenderResponse */
        TemplateRenderResponse: {
            /** Template Id */
            template_id: string;
            /** Template Name */
            template_name: string;
            /** Document Type */
            document_type: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** TranslateRequest */
        TranslateRequest: {
            /** Text */
            text: string;
            /** Target Lang */
            target_lang: string;
            /** Provider */
            provider?: string | null;
        };
        /** TranslateResponse */
        TranslateResponse: {
            /** Translated Text */
            translated_text: string;
            /** Provider */
            provider: string;
            /** Target Lang */
            target_lang: string;
        };
        /** UpdateWhatsAppStatusInput */
        UpdateWhatsAppStatusInput: {
            /** Linked */
            linked: boolean;
            /** Phone Number */
            phone_number?: string | null;
            /** Channel Name */
            channel_name?: string | null;
            /** Error */
            error?: string | null;
            /** Source */
            source?: string | null;
        };
        /** UsbDeviceItem */
        UsbDeviceItem: {
            /** Serial */
            serial: string;
            /** Drive */
            drive: string;
            /** Model */
            model?: string | null;
            /** Interface Type */
            interface_type?: string | null;
            /** Source */
            source?: string | null;
            registered?: components["schemas"]["RegisteredClienteSummary"] | null;
        };
        /** UsbDevicesResponse */
        UsbDevicesResponse: {
            /** Ok */
            ok: boolean;
            /** Count */
            count: number;
            /** Devices */
            devices: components["schemas"]["UsbDeviceItem"][];
            /** Runtime */
            runtime?: {
                [key: string]: unknown;
            } | null;
        };
        /** UsbProvisionRequest */
        UsbProvisionRequest: {
            /** Serial */
            serial: string;
            /** Drive */
            drive?: string | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Copy Installer
             * @default true
             */
            copy_installer: boolean;
        };
        /** UsbProvisionResponse */
        UsbProvisionResponse: {
            /** Ok */
            ok: boolean;
            /** Message */
            message?: string | null;
            /** Code */
            code?: string | null;
            /** Steps */
            steps?: {
                [key: string]: unknown;
            }[] | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** UserProfilePatch */
        UserProfilePatch: {
            /** Display Name */
            display_name?: string | null;
            /** Channel Id */
            channel_id?: string | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /** Integrations */
            integrations?: string[] | null;
            /** Automation Summary */
            automation_summary?: string | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
            ai_credentials?: components["schemas"]["AiCredentialsPatch"] | null;
            /** Saved Automations */
            saved_automations?: components["schemas"]["SavedAutomationDto"][] | null;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            /** Display Name */
            display_name?: string | null;
            /** Channel Id */
            channel_id?: string | null;
            /** Ai Provider Id */
            ai_provider_id?: string | null;
            /** Integrations */
            integrations?: string[] | null;
            /** Automation Summary */
            automation_summary?: string | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
            ai_credentials?: components["schemas"]["AiCredentialsResponse"] | null;
            /** Saved Automations */
            saved_automations?: components["schemas"]["SavedAutomationDto"][] | null;
            /** Pending Automation Results */
            pending_automation_results?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhatsAppChannelEventInput */
        WhatsAppChannelEventInput: {
            /**
             * Event
             * @enum {string}
             */
            event: "connecting" | "qr_ready" | "linked" | "heartbeat" | "disconnected" | "error" | "reconnecting";
            /** Phone Number */
            phone_number?: string | null;
            /** Channel Name */
            channel_name?: string | null;
            /** Error */
            error?: string | null;
            /** Source */
            source?: string | null;
        };
        /** WhatsAppChannelStatusResponse */
        WhatsAppChannelStatusResponse: {
            /**
             * Status
             * @default disconnected
             */
            status: string;
            /**
             * Linked
             * @default false
             */
            linked: boolean;
            /** Phone Number */
            phone_number?: string | null;
            /** Channel Name */
            channel_name?: string | null;
            /** Last Linked At */
            last_linked_at?: string | null;
            /** Last Disconnected At */
            last_disconnected_at?: string | null;
            /** Last Qr At */
            last_qr_at?: string | null;
            /** Last Heartbeat At */
            last_heartbeat_at?: string | null;
            /** Last Error At */
            last_error_at?: string | null;
            /**
             * Reconnect Required
             * @default false
             */
            reconnect_required: boolean;
            /**
             * Reconnect Attempts
             * @default 0
             */
            reconnect_attempts: number;
            /** Error */
            error?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_db_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_revoke_user_tokens_v1_admin_revoke_user_tokens_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeUserTokensRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_route_users_me_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_user_profile_route_users_me_profile_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfilePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_start_oauth_google_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleOAuthStartBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_callback_oauth_google_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    oauth_google_status_oauth_google_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_agenda_today_v1_chat_agenda_today_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendaTodayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_chat_reminder_v1_chat_reminders_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_chat_reminders_v1_chat_reminders_pending_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderPendingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_chat_reminders_v1_chat_reminders_ack_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReminderAckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_translate_v1_chat_translate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_summarize_v1_chat_summarize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummarizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_send_v1_chat_send_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_send_stream_v1_chat_send_stream_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_history_v1_chat__conversation_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_list_v1_chat_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_document_v1_documents_generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_v1_templates_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_v1_templates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentTemplateItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_template_v1_templates__template_id__render_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateRenderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telemetry_event_v1_telemetry_event_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_capabilities_v1_capabilities__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capability_detail_v1_capabilities__capability_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                capability_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_automation_v1_automations__auto_id__execute_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecuteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_automation_history_v1_automations__auto_id__history_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                auto_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_pending_results_v1_automations_results_ack_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pending_results_v1_automations_results_pending_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingResultsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_pendrive_v1_pendrive_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PendriveVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendriveVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_recovery_key_v1_pendrive_recovery_backup_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryBackupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recovery_v1_pendrive_recovery__cliente_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recovery_v1_pendrive_recovery__cliente_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_challenge_v1_pendrive_challenge_request_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_challenge_v1_pendrive_challenge_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recovery_login_v1_pendrive_recovery_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_new_pendrive_v1_pendrive_link_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PendriveLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendriveLinkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_provisioning_clients_v1_admin_pendrive_provisioning_clients_get: {
        parameters: {
            query?: {
                limit?: number;
                q?: string | null;
            };
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisioningClientsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_validate_provisioning_serial_v1_admin_pendrive_provisioning_validate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvisioningValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvisioningValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_recovery_v1_admin_pendrive_recovery__cliente_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                cliente_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usb_devices_v1_usb_devices_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsbDevicesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provision_usb_v1_usb_provision_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsbProvisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsbProvisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_by_serial_v1_usb_client_by_serial__serial__get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-key"?: string | null;
            };
            path: {
                serial: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientBySerialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_v1_whatsapp_channel_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppChannelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_v1_whatsapp_channel_status_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWhatsAppStatusInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppChannelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_event_v1_whatsapp_channel_events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatsAppChannelEventInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppChannelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconnect_v1_whatsapp_channel_reconnect_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppChannelStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
